<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Ecpass Pay' => '联行支付',
    'Micro Payment' => '',
    'Mweb Payment' => '',
    'Native Payment' => '',
    'Wallet Pay' => '钱包支付',
    'Wechat Pay' => '微信支付',
    'Alipay' => '支付宝',
    'App Payment' => 'App支付',
    'Batch Deletion' => '批量删除',
    'Completion of payment.' => '支付完成。',
    'Created At' => '创建时间',
    'Currency' => '币种',
    'Delete Payment' => '删除支付',
    'ID' => '交易号',
    'Jsapi Payment' => 'JSAPI支付',
    'Manage Payment' => '付款管理',
    'Model' => '模型',
    'Model ID' => '模型ID',
    'Money' => '金额',
    'Office Payment' => '离线支付',
    'Pay ID' => '付款ID',
    'Pay IP' => '付款IP',
    'Pay Note' => '备注',
    'Pay State' => '支付状态',
    'Pay Type' => '付款类型',
    'Payment' => '付款',
    'Payment Gateway' => '支付网关',
    'Payment Name' => '事由',
    'Qpay' => 'QQ支付',
    'State Close' => '已关闭',
    'State Error' => '错误',
    'State Failed' => '支付失败',
    'State Not Pay' => '未支付',
    'State Refund' => '转入退款',
    'State Revoked' => '已撤销',
    'State Success' => '支付成功',
    'Sweep two-dimensional code, pay immediately' => '扫描二维码，立即支付',
    'The gateway does not support the current currency!' => '网关不支持该货币！',
    'The server is busy. Please try again!' => '服务器繁忙，请重试！',
    'This id has already been taken' => '此交易号已被占用',
    'Trade State' => '交易状态',
    'Trade Type' => '交易类型',
    'Update Payment' => '更新支付',
    'Updated At' => '更新时间',
    'User ID' => '用户ID',
];
